baseURL = "/"
languageCode = "en-us" # Default language
title = "Geroen Joris Tech Blog"
theme = "DoIt"

[params]
  description = "A personal, professional, and visually appealing tech blog focusing on AWS, DevSecOps, software architecture, and security."
  images = ["/images/avatar.webp"] # Using example's avatar, we can change this later

  [params.author]
    name = "Geroen Joris"
    link = "https://github.com/gjoris"

  [params.home]
    [params.home.posts]
      enable = true
      paginate = 10
      sections = ["posts"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true

[taxonomies]
  category = "categories"
  tag = "tags"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Geroen Joris Tech Blog"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Home"
        url = "/"
        weight = 10
      [[languages.en.menu.main]]
        name = "About"
        url = "/about/"
        weight = 20
      [[languages.en.menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 30
  [languages.nl]
    languageName = "Nederlands"
    weight = 2
    title = "Geroen Joris Tech Blog"
    [languages.nl.menu]
      [[languages.nl.menu.main]]
        name = "Home"
        url = "/nl/"
        weight = 10
      [[languages.nl.menu.main]]
        name = "Over Mij"
        url = "/nl/about/"
        weight = 20
      [[languages.nl.menu.main]]
        name = "Contact"
        url = "/nl/contact/"
        weight = 30