site:
  name: Geroen Joris | Tech Blog
  site: 'https://gjoris.github.io/'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: null # or your ID

# Default SEO metadata
metadata:
  title:
    default: Geroen Joris | Tech Blog
    template: '%s — Geroen Joris | Tech Blog'
  description: "A professional tech blog about AWS, DevSecOps, software architecture, and security."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Geroen Joris | Tech Blog
    images:
      - url: '~/assets/images/IMG_0007.jpg' # Update with your image
        width: 150
        height: 150
    type: website
  twitter:
    handle: null # Your Twitter handle
    site: null # Your Twitter site
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
